config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 	 '/signup', to: 'users#new'
  get 	 '/login', to: 'sessions#new'
  post 	 '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy, :index]
  get 'friends', to: 'friendships#index'
end

app/models/user.rb
class User < ApplicationRecord
	
	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 250 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy

	def request_friendship(target_user)
    friendship = friendships.create(user_id: self.id, friend_id: target_user.id)
    target_user.inverse_friendships << friendship
  end

  def all_friendships
    Friendship.where('friend_id = ? OR user_id = ?', self.id, self.id)
  end

  def relationship_status(target_user)
    if all_friends.include?(target_user)
      self.find_friendship(target_user).status
    else
      'Not Friends'
    end
  end

  def is_friend?(target_user)
    self.all_friends.include?(target_user)
  end

  def find_friendship(target_user)
    friend = Friendship.where("friend_id = ? AND user_id = ?", target_user.id, self.id).take
    inverse_friend = Friendship.where("friend_id = ? AND user_id = ?", self.id, target_user.id).take
    friend.nil? ? inverse_friend : friend
  end

  def all_friends
    # needs serious refactoring
    requested_friends = self.friends
    requesting_friends = self.inverse_friends
    all_friends = []
    User.all.each do |user|
      all_friends << user if requested_friends.include?(user)
      all_friends << user if requesting_friends.include?(user)
    end
    all_friends
  end


	def feed
		Post.where("user_id = ?", id)
	end

	def likes?(post)
    self.likes.include?(user_like(post))
  end

  def user_like(post)
    Like.where(user_id: self.id, post_id: post.id).take
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @current_user = current_user
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def show
    @current_user = current_user
  	@user = User.find(params[:id])
  end


  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash[:success] = "Welcome, Adios!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private

	  def user_params
	  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end

	  def correct_user
	  	@user = User.find(params[:id])
	  	redirect_to(root_url) unless current_user?
	  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <% unless user.id == @current_user.id %>
      <li>
        <%= link_to user.name, user_path(user) %>
        <span>
          <% if current_user.is_friend?(user) %>
            <% if current_user.find_friendship(user).status == 'pending' %>
              (pending)
            <% else %>
              (<%= link_to 'unfriend',  @current_user.find_friendship(user), 
                                        method: :delete, 
                                        data: { confirm: "You sure?"} %>)
            <% end %>
          <% else %>
            (<%= button_to 'add friend', friendships_path,  method: :post,  
                                                            class: "text-only", 
                                                            params: { friend_id: user.id } %>)
          <% end %>
          
        </span>
      </li>
    <% end %>
  <% end %>  
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email, "Email" %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Create Account" %>

	<% end %>
</div>

app/views/users/show.html.erb
<h2><%= render 'shared/user_info' %></h2>

<% unless @current_user == @user %>
  <% if @current_user.is_friend?(@user) %>
    <p>Friendship Status: <%= @current_user.relationship_status(@user) %>(
        <%= link_to "unfriend", @current_user.find_friendship(@user), 
                                method: :delete,
                                data: { confirm: "You sure?"} %>)</p>
  <% else %>
    <span>Not Friends. (<%= render 'friendships/add_friend', user: @user %>)</span>
  <% end %>
<% else %>
<% end %>

<ul class="profile-posts">
  <% @user.posts.each do |post| %>
    <li>
      <p><%= link_to post.content, post_path(post)  %></p>
      <p>Posted <%= link_to "#{time_ago_in_words(post.created_at)} ago"%></p>
    </li>
  <% end %>  
</ul>