config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 	 '/signup', to: 'users#new'
  get 	 '/login', to: 'sessions#new'
  post 	 '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy, :index]
  get 'friends', to: 'friendships#index'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  validates   :user_id, :friend_id, presence: true
  validate    :cannot_friend_self
  validates   :status,  inclusion: { in: ['pending', 'friends'] }

  private 

    def cannot_friend_self
      if friend_id == user_id
        errors.add(:friend_id, "can't be the same as the User's id.")
      end
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include FriendshipsHelper
  before_action :already_friends, only: [:create]

  def create
    @target_user = User.find(params[:friend_id])
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:success] = "Friend invite sent."
    else
      flash[:danger] = "Couldn't add friend."
    end
    redirect_to user_url(@target_user)
  end

  def update
    @friendship = Friendship.find(params[:id])
    @friendship.update_attribute(:status, 'friends')
    redirect_to root_path
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @target_user = other_user_in_friendship(@friendship)
    Friendship.find(@friendship.id).destroy
    flash[:notice] = "Unfriended #{@target_user.name}"
    redirect_to friends_path
  end

  def index
    @user = current_user
    @friendships = current_user.all_friendships
  end

  private 

    def already_friends
      target_user = User.find(params[:friend_id])
      if friendship_exists?(target_user) || friendship_exists?(current_user, target_user)
        flash[:message] = "A friendship already exists with that person."
        redirect_to user_path(target_user)
      end
    end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper

  def friendship_exists?(target_user, user=current_user)
    Friendship.where("user_id = ? AND friend_id = ?", user.id, target_user.id).any?
  end

  def other_user_in_friendship(friendship)
    friend = User.find(friendship.friend_id)
    user = User.find(friendship.user_id)
    current_user == friend ? user : friend 
  end

end

app/views/friendships/_add_friend.html.erb
<%= button_to 'add friend', friendships_path,  method: :post, class: "text-only", params: { friend_id: user.id } %>

app/views/friendships/_friend.html.erb
<%= friendship.friend.name %>
<% if friendship.status == "pending" %>
  (pending)
<% else %>  
  (<%= link_to "unfriend", friendship, :method => :delete %>)
<% end %>   

app/views/friendships/_inverse_friend.html.erb
<%= friendship.user.name %>
<% if friendship.status == "pending" %>
  (<%= link_to "accept", friendship_path(friendship, @user), method: :patch, action: :update %>)
<% else %>  
  (<%= link_to "unfriend", friendship, :method => :delete %>)
<% end %>   

app/views/friendships/index.html.erb
<h1>Your Friends</h1>

<ul id="friend-listing">
  <% @friendships.each do |friendship| %>
    <li class="friend_listing">    
      <% if @user.id == friendship.friend_id %>
        <%= render 'friendships/inverse_friend', friendship: friendship %>      
      <% else %>  
        <%= render 'friendships/friend', friendship: friendship %>      
      <% end %>   
    </li>
  <% end %>  
</ul>