config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 	 '/signup', to: 'users#new'
  get 	 '/login', to: 'sessions#new'
  post 	 '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy, :index]
  get 'friends', to: 'friendships#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 6, maximum: 5000 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@like = current_user.user_like(@post)
	end

	def new
		@post = Post.new
	end
		
	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Posted on your pages"
			redirect_to post_path(post)
		else
			flash[:danger] = "Unable to post update"
			render 'new'
		end
	end

	def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated."
      redirect_to @post
    else
      flash.now[:danger] = "Couldn't update post - try again."
      render 'edit'
    end
  end

	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private
		
		def post_params
			params.require(:post).permit(:user_id, :content)
		end

		def correct_user
			@post = current_user.posts.find_by(id: params[:id])
			redirect_to root_url if @post.nil?
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<%= form_for(@post.comments.build) do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit %>
<% end %>

app/views/posts/_edit_comment.html.erb
<%= form_for(comment) do |f| %>
  <%= f.label :body, 'Edit: ' %>
  <%= f.text_field :body %>

  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  
  <%= f.label :content %>
  <%= f.text_field :content %>
  
  <%= f.submit %>

<% end %>

app/views/posts/_like_form.html.erb
<%= form_for @post.likes.build, html: { class: 'new_like text-only'} do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit 'LIKE', class: 'text-only' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>
<% if current_user == @post.user %>
  <%= link_to 'delete post', post_path(@post), method: :delete, data: { confirm: "You sure?" } %>
<% end %>

app/views/posts/index.html.erb
<h1>Your Feed</h1>

<% if @posts.any? %>
  <% @posts.each do |post| %>

    <ul>
      <li class="post_item">
        <a href="<%= post_path(post) %>"><em>Posted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %></em></a> 
        <p><%= post.content %></p>

        (<%= pluralize(post.likes.count, 'like') %>)
        (<%= link_to "#{post.comments.count} comments", post %>)
      </li>
    </ul>

  <% end %>

<% else %>
  <p>It's lonely here! Try <%= link_to("writing a post", new_post_path) %> to spruce things up!</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<h4><%= @post.user.name %> posted <%= time_ago_in_words(@post.created_at) %> ago:</h4>
<p><%= @post.content %></p>

<div>
<span>(<%= pluralize(@post.likes.count, 'like') %>)</span> 
<% unless current_user.likes?(@post) %>
  <%= render 'like_form' %>
<% else %>
  <%= link_to 'UNLIKE', like_path(@like.id), method: :delete, class: 'text-only' %>
<% end %>
</div>

<% if current_user == @post.user %>
  <%= link_to '(edit post)', edit_post_path(@post) %>
<% end %>

<% if @comments %>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <% if comment.user == current_user %>
          <p><%= link_to 'You', current_user %> said 
              <%= time_ago_in_words(comment.created_at) %> ago. 
              (<%= link_to 'delete', comment, method: :delete, data: { confirm: 'You sure?'} %>)
          </p>
          <%= render 'edit_comment', comment: comment %>
        <% else %>
         <p><%= link_to comment.user.name, comment.user %> <%= time_ago_in_words(comment.created_at) %> ago.</p>
        <% end %>
        <p><%= comment.body %></p>
      </li>
    <% end %>    
  </ul>
<% end %>

<p><strong>New Comment</strong></p>
<%= render 'comment_form' %>