config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 	 '/signup', to: 'users#new'
  get 	 '/login', to: 'sessions#new'
  post 	 '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy, :index]
  get 'friends', to: 'friendships#index'
end

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container">
    <%= link_to "FacebookClone", root_path, id: "logo" %>
    <nav>
      <ul class="header">
        <% if logged_in? %>
          <li><%= link_to "Friends", users_path %></li>            
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>| FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>